# Site settings
title: Alp Turkmen
name: Alp Turkmen
# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: LinkedIn
   url: https://www.linkedin.com/in/alp-turkmen/


#Any buzzword skills you want to include
skills:
 - Digital Marketing
 - Environmental Design
 - CAD, Java, C++

#Work experience is required
roles:
 - title: Device Management Intern
   start: May 2018
   end: Ongoing
   employer: Rogers Communications

- title: Founder
   start: 2017
   end: 2018
   employer: StuLance
   description: With over 50 connections made in real time between beta testers and over 1/2 of the matchups leading to a completed job, StuLance is a powerful emerging platform that connects students to freelance opportunities around campus.
 - title: Web/IT Coordinator
   start: 2017
   end: Ongoing
   employer: Queen's Global Energy Conference
   description: Previously First Year Rep. I am currently responsible for all of QGEC's web assets.
  - title: Sponsorship Coordinator
   start: 2018
   end: Ongoing
   employer: Queen's Global Innovation Conference
  
#Education is required
education:
 - level: Bachelor of Applied Science & Certificate In Bussiness
   date: 2021
   school: Queen's University & Smith School Of Bussiness


